/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#0d0e12",
        "outline": "#909194",
        "on-primary": "#303031",
        "tertiary-fixed": "#e4e2e3",
        "on-tertiary-fixed": "#1b1b1c",
        "on-error": "#690005",
        "on-surface-variant": "#c6c6ca",
        "primary-fixed-dim": "#c8c6c7",
        "tertiary-container": "#c8c6c7",
        "on-secondary-fixed-variant": "#574500",
        "surface-container": "#1e1f24",
        "outline-variant": "#45474a",
        "tertiary": "#e4e2e3",
        "on-primary-container": "#535253",
        "surface-variant": "#343439",
        "tertiary-fixed-dim": "#c8c6c7",
        "on-secondary-fixed": "#231a00",
        "surface-container-low": "#1a1b20",
        "on-tertiary-fixed-variant": "#474748",
        "on-primary-fixed": "#1b1b1c",
        "secondary-container": "#ae8d10",
        "secondary": "#e9c349",
        "error-container": "#93000a",
        "primary-container": "#c8c6c7",
        "inverse-primary": "#5f5e5f",
        "secondary-fixed": "#ffe087",
        "on-error-container": "#ffdad6",
        "surface-bright": "#38393d",
        "primary": "#e4e2e3",
        "surface": "#121317",
        "inverse-surface": "#e3e2e7",
        "secondary-fixed-dim": "#e9c349",
        "background": "#121317",
        "on-surface": "#e3e2e7",
        "on-background": "#e3e2e7",
        "surface-container-high": "#292a2f",
        "surface-container-highest": "#34353a",
        "error": "#ffb4ab",
        "on-secondary": "#303031",
        "surface-variant-high": "#3f4045",
      },
      fontFamily: {
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'headline-lg': ['"Hanken Grotesk"', 'Inter', 'sans-serif'],
        'headline-md': ['"Hanken Grotesk"', 'Inter', 'sans-serif'],
        'headline-xl': ['"Hanken Grotesk"', 'Inter', 'sans-serif'],
        'label-md': ['Inter', 'system-ui', 'sans-serif'],
        'label-sm': ['Inter', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['3.5rem', { lineHeight: '1.1', fontWeight: '800' }],
        'headline-lg': ['2.5rem', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['1.25rem', { lineHeight: '1.3', fontWeight: '700' }],
        'body-lg': ['1.125rem', { lineHeight: '1.6' }],
        'body-md': ['0.9375rem', { lineHeight: '1.6' }],
        'label-md': ['0.875rem', { lineHeight: '1.4', fontWeight: '500' }],
        'label-sm': ['0.75rem', { lineHeight: '1.4', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
